version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Install phase

  pre_build:
    commands:
      - echo Pre-Build phase

  build:
    commands:
      - echo Build Starting on `date`
      - ./gradlew clean build -x test

artifacts:
  files:
    - target/*.war
