version: 0.2

phases:
  build:
    commands:
      - echo Build Starting
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo post build start
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'